// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import {
  fileDesc,
  messageDesc,
  enumDesc,
  tsEnum,
  } from "@bufbuild/protobuf/codegenv1";


export const file_stately =
  /*@__PURE__*/
  fileDesc("Cg1zdGF0ZWx5LnByb3RvEhFzdGF0ZWx5LmdlbmVyYXRlZCIXCgVMYWJlbBIOCgRuYW1lGAEgASgJQgAimgIKC091dGFnZUV2ZW50EhIKCG91dGFnZUlkGAEgASgEQgASEAoGcmVwb0lkGAIgASgJQgASEgoIcnVubmVySWQYAyABKARCABIxCgZzdGF0dXMYBCABKA4yHy5zdGF0ZWx5LmdlbmVyYXRlZC5SdW5uZXJTdGF0dXNCABITCglzdGFydGVkQXQYBSABKBJCABIUCgpyZXNvbHZlZEF0GAYgASgSQgASFQoLZGVzY3JpcHRpb24YByABKAlCABIaChBub3RpZmljYXRpb25TZW50GAggASgIQgASEwoJY3JlYXRlZEF0GAkgASgSQgASEwoJdXBkYXRlZEF0GAogASgSQgASFAoKcnVubmVyTmFtZRgLIAEoCUIAOgAiggEKClJlcG9zaXRvcnkSEAoGcmVwb0lkGAEgASgJQgASDwoFb3duZXIYAiABKAlCABIOCgRuYW1lGAMgASgJQgASEgoIaXNBY3RpdmUYBCABKAhCABITCgljcmVhdGVkQXQYBSABKBJCABIWCgxsYXN0U3luY2VkQXQYBiABKBJCADoAIpcCCgZSdW5uZXISEgoIcnVubmVySWQYASABKARCABIQCgZyZXBvSWQYAiABKAlCABIOCgRuYW1lGAMgASgJQgASMQoGc3RhdHVzGAQgASgOMh8uc3RhdGVseS5nZW5lcmF0ZWQuUnVubmVyU3RhdHVzQgASEQoHZW5hYmxlZBgFIAEoCEIAEgwKAm9zGAYgASgJQgASKgoGbGFiZWxzGAcgAygLMhguc3RhdGVseS5nZW5lcmF0ZWQuTGFiZWxCABIUCgpsYXN0U2VlbkF0GAggASgSQgASFQoLZmlyc3RTZWVuQXQYCSABKBJCABITCgljcmVhdGVkQXQYCiABKBJCABITCgl1cGRhdGVkQXQYCyABKBJCADoAKqcBCgxSdW5uZXJTdGF0dXMSHAoYUnVubmVyU3RhdHVzX1VOU1BFQ0lGSUVEEAASFwoTUnVubmVyU3RhdHVzX09OTElORRABEhgKFFJ1bm5lclN0YXR1c19PRkZMSU5FEAISFQoRUnVubmVyU3RhdHVzX0JVU1kQAxIYChRSdW5uZXJTdGF0dXNfVU5LTk9XThAEEhUKEVJ1bm5lclN0YXR1c19JRExFEAViBnByb3RvMw==");

/**
 * Describes the message stately.generated.Label.
 * Use `create(LabelSchema)` to create a new message.
 */
export const LabelSchema = /*@__PURE__*/ messageDesc(file_stately, 0);


/**
 * Describes the message stately.generated.OutageEvent.
 * Use `create(OutageEventSchema)` to create a new message.
 */
export const OutageEventSchema = /*@__PURE__*/ messageDesc(file_stately, 1);


/**
 * Describes the message stately.generated.Repository.
 * Use `create(RepositorySchema)` to create a new message.
 */
export const RepositorySchema = /*@__PURE__*/ messageDesc(file_stately, 2);


/**
 * Describes the message stately.generated.Runner.
 * Use `create(RunnerSchema)` to create a new message.
 */
export const RunnerSchema = /*@__PURE__*/ messageDesc(file_stately, 3);


/**
 * Describes the enum stately.generated.RunnerStatus.
 */
export const RunnerStatusSchema = /*@__PURE__*/ enumDesc(file_stately, 0);

export const RunnerStatus = /*@__PURE__*/ tsEnum(RunnerStatusSchema);
