// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import { createClient as createGenericClient, StatelyError } from "@stately-cloud/client";
import {
  OutageEventSchema,
  RepositorySchema,
  RunnerSchema,
  LabelSchema,
} from "./stately_pb.js";

export const typeToSchema = {
  // itemTypes
  "OutageEvent": OutageEventSchema,
  "Repository": RepositorySchema,
  "Runner": RunnerSchema,

  // objectTypes
  "Label": LabelSchema,
};


/** The version of the schema that this client was generated for. */
const SCHEMA_VERSION_ID = 2;
const SCHEMA_ID = 3168601782134171;


export function createClient(storeId, opts) {
  
  return createGenericClient(storeId, typeToSchema, SCHEMA_VERSION_ID, SCHEMA_ID, opts);
  
}

if (createGenericClient.length < 4) {
  throw new Error("Your version of @stately-cloud/client is too old. Please update to the latest version.");
}
