// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import type {
  DatabaseClient as GenericDatabaseClient,
  StoreID,
  ClientOptions,
} from "@stately-cloud/client";
import type {
  OutageEvent,
  Repository,
  Runner,
  OutageEventSchema,
  RepositorySchema,
  RunnerSchema,
  LabelSchema,
} from "./stately_pb.js";

export declare const itemTypeToSchema: {
  OutageEvent: typeof OutageEventSchema;
  Repository: typeof RepositorySchema;
  Runner: typeof RunnerSchema;
  Label: typeof LabelSchema;
};

// AllItemTypes is a convenience type that represents all item type names in your schema.
export type AllItemTypes = "OutageEvent" | "Repository" | "Runner";

// AnyItem is a convenience type that represents any item shape in your schema.
export type AnyItem = OutageEvent | Repository | Runner;

// DatabaseClient is a database client that has been customized with your schema.
export type DatabaseClient = GenericDatabaseClient<
  typeof itemTypeToSchema,
  AllItemTypes
>;

// createClient creates a new database client with your schema.
export declare function createClient(
  storeId: StoreID,
  opts?: ClientOptions,
): DatabaseClient;
